# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchTextLE = QtWidgets.QLineEdit(self.tab)
        self.searchTextLE.setObjectName("searchTextLE")
        self.horizontalLayout.addWidget(self.searchTextLE)
        self.searchBtn = QtWidgets.QPushButton(self.tab)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.searchInLE = QtWidgets.QLineEdit(self.tab)
        self.searchInLE.setObjectName("searchInLE")
        self.horizontalLayout_3.addWidget(self.searchInLE)
        self.dirBtn = QtWidgets.QPushButton(self.tab)
        self.dirBtn.setObjectName("dirBtn")
        self.horizontalLayout_3.addWidget(self.dirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.recurseCB = QtWidgets.QCheckBox(self.tab)
        self.recurseCB.setObjectName("recurseCB")
        self.verticalLayout.addWidget(self.recurseCB)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.resultsWidget = QtWidgets.QTableWidget(self.tab)
        self.resultsWidget.setObjectName("resultsWidget")
        self.resultsWidget.setColumnCount(5)
        self.resultsWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultsWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.resultsWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.regexCB = QtWidgets.QCheckBox(self.tab_2)
        self.regexCB.setGeometry(QtCore.QRect(10, 20, 88, 22))
        self.regexCB.setObjectName("regexCB")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchTextLE.setPlaceholderText(_translate("MainWindow", "Type word/phrase to search"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Search in:"))
        self.dirBtn.setText(_translate("MainWindow", "Directory..."))
        self.recurseCB.setText(_translate("MainWindow", "Search recursively"))
        self.label_2.setText(_translate("MainWindow", "Results:"))
        item = self.resultsWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.resultsWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.resultsWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.resultsWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Directory"))
        item = self.resultsWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Search"))
        self.regexCB.setText(_translate("MainWindow", "Use RegEx"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
